services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: si_cooperative_cartoes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    container_name: spark_container
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Spark UI
    depends_on:
      - postgres

  spark-worker:
    image: bitnami/spark:latest
    volumes:
      - ./data:/app/data
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark

  etl:
    build: .
    container_name: etl_container
    depends_on:
      - postgres
      - spark
    environment:
      DB_CONNECTION: "jdbc:postgresql://postgres:5432/si_cooperative_cartoes"
    volumes:
      - ./data:/app/data
      - .:/app
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark:7077
      --packages com.databricks:spark-xml_2.12:0.17.0
      --jars /app/jars/postgresql-42.7.3.jar
      /app/ingestao_dados.py

volumes:
  postgres_data: