version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: si_cooperative_cartoes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    container_name: spark_container
    environment:
      - SPARK_MODE=master
      - SPARK_NETWORK_TIMEOUT=600s
      - SPARK_EXECUTOR_HEARTBEATINTERVAL=120s
    ports:
      - "8080:8080"  # Spark UI
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    volumes:
      - ./data:/app/data

  etl:
    build: .
    container_name: etl_container
    depends_on:
      - postgres
      - spark
    environment:
      DB_CONNECTION: "jdbc:postgresql://postgres:5432/si_cooperative_cartoes"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    command: sh -c "/app/scripts/run_etl.sh"

volumes:
  postgres_data: